join-message:
  enabled: true
  permission: "klaby.notify"
  message: "&7%player_name% &ejoined using &b&lLabyMod&e." # Supports PlaceholderAPI
banner:
  enabled: false
  link: "https://i.imgur.com/" # Imgur URL
menu:
  # Types:
  # NONE - Does nothing
  # CLIPBOARD - Copies the value to the clipboard
  # RUN_COMMAND - Runs the command in the value as a the player
  # SUGGEST_COMMAND - Open the chat and suggest to run the command in the value
  # OPEN_BROWSER - Open the link in the value
  # Placeholders:
  # {name} - The player name
  friend:
    name: "&aAdd as friend"
    type: "RUN_COMMAND"
    value: "friends add {name}"
  forum:
    name: "&eOpen forum profile"
    type: "OPEN_BROWSER"
    value: "https://your_webpage/users/{name}"
  kick:
    name: "&cKick from the server"
    type: "SUGGEST_COMMAND"
    value: "kick {name} "
    permission: "klaby.staff"
server-name:
  friends:
    enabled: true
    name: "&eYour Server" # Supports color codes
  discord:
    enabled: true
    name: "Your Server"
economy:
  enabled: true # This system only works with the Essentials economy. More economies and placeholders will be supported soon.
  icon:
    enabled: false
    url: "https://i.imgur.com/"
subtitle:
  enabled: true
  subtitles:
    staff:
      size: 0.8 # number between 0.8 and 1.6 (minecraft default)
      text: "&eStaff member" # Supports PlaceholderAPI
      permission: "klaby.staff"
    vip:
      size: 0.8
      text: "&6&lVIP"
      permission: "klaby.vip"